name = "TotalLeastSquares"
uuid = "4d86fc1a-bdb3-11e8-0c66-91cf18e9d32b"
authors = ["Fredrik Bagge Carlson <cont-frb@ulund.org>"]
version = "0.1.0"

[deps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
